import Foundation

public extension Dataset {
    enum LoadError: Error, LocalizedError {
        case missingResource

        public var errorDescription: String? {
            "facilities.json is missing from the ParkingKit bundle."
        }
    }

    /// The dataset shipped inside the app. Generated by `tools/build_dataset.py`.
    static func bundled() throws -> Dataset {
        guard let url = Bundle.module.url(forResource: "facilities", withExtension: "json") else {
            throw LoadError.missingResource
        }
        return try JSONDecoder().decode(Dataset.self, from: Data(contentsOf: url))
    }

    func facilities(in system: ParkingSystem) -> [Facility] {
        facilities.filter { $0.system == system }
    }

    func facility(lotId: String) -> Facility? {
        facilities.first { $0.lotId == lotId }
    }

    /// Facilities a person could actually choose to park in. Excludes tiers that
    /// are never available to an individual - service/restricted areas and
    /// contractor lots - so the "free now" list stays honest.
    var parkable: [Facility] {
        facilities.filter { ![.restricted, .contractor, .other].contains($0.tier) }
    }
}
